album/urls.py
from django.contrib import admin
from django.urls import path, include
from album import views

urlpatterns = [
    path('', views.base, name="base"),
   #path('', views.Main, name='base1.html'),
    path( '', views.first_view, name="first view"),
    path('category/', views.CategoryListView.as_view(), name='category-list'),      
    #path('category/',views.category, name='category'),

    
    path('category/<int:category_id>/detail/', views.category_detail, name='category-detail'),
    
    
    #path('category/', views.CategoryListView.as_view(), name='category-detail'),
    path('photo/', views.Photo, name='photo-list'),
    #path('photo/', views.PhotoListView.as_view(), name='photo-list'),
    path('photo/<int:pk>/detail/', views.PhotoDetailView.as_view(), name='photo-detail'),
    path('photo/<int:pk>/update', views.PhotoUpdate.as_view(), name='photo-update'),
    path('photo/create', views.PhotoCreate.as_view(), name='photo-create'),
    path('photo/<int:pk>/delete', views.PhotoDelete.as_view(), name='photo-delete'),
]

myapps/urls.py
#from django.conf.urls import patterns, include
from django.contrib import admin
from django.urls import path, include
from album import views

#urlpatterns = [
 #   path('admin/', admin.site.urls),
#]
urlpatterns = [
    path('admin/', admin.site.urls),
     #path('album/',include('album.url'), name='main'),
    path('album/', include('album.urls') ),
        
]

album/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.urls import reverse

class Category(models.Model):
    """Categorias para clasificar las fotos"""
    name  = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class Photo(models.Model):
    """ Fotos del album """
    category = models.ForeignKey(Category, null=True, blank=True,on_delete=models.PROTECT   )
    title = models.CharField(max_length=50, default='No title')
    photo = models.ImageField(upload_to='photos/')
    pub_date = models.DateField(auto_now_add=True)
    favorite = models.BooleanField(default=False)
    comment = models.TextField(max_length=200, blank=True)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('photo-list')
        
    @receiver(post_delete, sender=photo)
    def photo_delete(sender, instance, **kwargs):
        """Borra los ficheros de las fotos que se eliminen."""
        instance.photo.on_delete(False)

album/views.py
from django.shortcuts import render
from django.http import HttpResponse
from album.models import Category
from album.models import Photo
from django.views.generic import ListView,DetailView
from django.views.generic import UpdateView,CreateView,DeleteView
from django.urls import reverse_lazy

#def first_view(request):
 #   return HttpResponse("<h1>Esta </h1> es la primera vista!<br><input type='text'> <br> <input type=button value=BOTON>")
#def selection_detail(request,selection_id):
 #   selection = Selection.objects.get(id=selection_id)# hace referencia a un select ... where 
  #  context = {'object': selection}
   # return render(request, 'album/selection_detail.html',context)

def first_view(request):
    return HttpResponse('Esta es mi primera vista')

def base(request):
   return render(request,'base.html')
    
def category(request):
    category_list = Category.objects.all()
    context = {'object_list': category_list}
    return render(request, 'album/category_list.html', context)

def category_detail(request, category_id):
    category = Category.objects.get(id=category_id)
    context = {'object': category}
    return render(request, 'album/category_detail.html', context)


def Photo(request):
    photo_list = Category.objects.all()
    context = {'object_list': photo_list}
    return render(request, 'album/photo_detail.html', context)
    
class CategoryListView(ListView):
 model = Category

class PhotoListView(ListView):
 model = Photo

class PhotoDetailView(DetailView):
 model = Photo

class PhotoUpdate(UpdateView):
   model = Photo

class PhotoCreate(CreateView):
   model = Photo

class PhotoDelete(DeleteView):
   model = Photo
   success_url = reverse_lazy('photo-list')

album/templates/album/category.html
{{ object_list }}

album/templates/album/category_detail.html
{% extends 'base.html' %}
{% load static %}

{% block section %}
    <h2>{{ object.name }}</h2>
    <hr>
{% endblock section %}
{% block maincontent %}
<h3>utiliza category_detail.html</h3>
<div>
    <table border="1px">
        <tr>
            {% for p in object.photo_set.all %}
                <td>
                    <div>{{ p.title }}</div>
                        <div>
                                <a href="{% url 'photo-detail' p.id %}" >​                      
                                <img src="{% static p.photo.url %}" style ​="width:200px;height:200px" ​/>

                            </a >
                        </div>
                </td>
{% endfor %}
</tr​>
</table>
</div>
{% endblock maincontent %}

album/templates/album/category_list.html
{% extends 'base.html' %}
{% block section %}
    <h2>Category</h2>
    <h3>utiliza category_list.html</h3>
    <hr>
{% endblock section %}
{% block maincontent %}
    <div>
{% for c in object_list %}
<a href="{% url 'category-detail' c.id %}"> 
   
                {{ c.name }}
            </a>
{% endfor %}
    </div>
{% endblock maincontent %}

album/templates/album/photo_confirm_delete.html
{% extends 'base.html' %}
{% block maincontent %}
<form ​ ​action ​="" ​ ​method ​="post"​>
    {% csrf_token %}<p​>Delete "{{ object.title }}"?</p>
<input ​ ​type ​="submit" ​ ​value ​="Confirm" ​ />
<a ​ ​class ​=​'btn' ​ ​href="{% url 'photo-list' %}"​>Cancel</a>
</form>
{% endblock maincontent %}

album/templates/album/photo_detail.html
{% extends 'base.html' %}
{% load static %}

{% block section %}
    <h2>
        {{ object.title }}
        {% if object.favorite %}
            &#9733;
        {% else %}
            &#9734;
        {% endif %}
        {% if object.category_id %}
        ( <a href="{% url 'category-detail' object.category_id %}" >{{ object.category }}</a> ) 
        {% endif %}
    </h2>
    <p><strong>comments: </strong>{{ object.comment|default:"no comments" }}</p>
    <!--a href="{% url 'photo-update' object.id %}">edit</a> ​
    <a href="{% url 'photo-delete' object.id %}">delete</a-->     
    <hr>
{% endblock section %}

{% block maincontent %}
<div>
    <div>
        <img ​ ​src ​="{% static object.photo.url %}" style="width:550px;height:420px" ​/>
    </div>
    
</div>
{% endblock maincontent %}

album/templates/album/photo_form.html
{% extends "base.html" %}
{% block maincontent %}
<form enctype=​"multipart/form-data" ​ ​method=​"post" ​>
    {% csrf_token %}
    {{ form.as_p }}
<button ​ ​type="submit" >Save</button>
<a class="btn" href="{% url 'photo-list' %}">Cancel</a>

</form>
{% endblock maincontent%}

album/templates/album/photo_list.html
{% extends 'base.html' %}

{% block section %}
    <h2>Fotos</h2>
    <hr>
{% endblock section %}
{% block maincontent %}
    <div>
{% for c in object_list %}
    <a href="{% url 'photo-list' %}">
                {{ c.title }}
            </a>
{% endfor %}
    </div>
{% endblock maincontent %}

templates/base.html
<html>
<headlang="en">
 <metacharset="UTF-8">
 <linkrel="stylesheet"
 href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <linkrel="stylesheet"
 href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
  <script
 src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script
 src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script> 
 <title>Album</title>
</head>
    <body>
        <!-- NavBar -->
​<nav class="navbar navbar-default" ><div class="container-fluid">
    
</div></nav>

    <h1>Album</h1>
    <ul>
        
        <li>
             <a href="{% url 'category-list' %}">Category</a>
        </li>
        <li>
            <a href="{% url 'photo-list' %}">Photo</a>
        </li>
        <li>
                <a href="{%  url 'photo-list' %}">upload</a>
        </li>
    </ul>
    <hr>
        <div>
            {% block section %}
            {% endblock section %}
        </div>
        <div>
            {% block maincontent %}
            {% endblock maincontent %}
        </div>
    </body>
</html>